using MyDictionary.Models;

namespace MyDictionaryAPI.Mapping
{
    /// <summary>
    /// Manual mapping between Entity (LibraryModels) and Term DTOs.
    /// </summary>
    public static class TermMapper
    {
        // ENTITY -> DTO (for responses)
        public static TermDto ToDto(this LibraryModels entity)
        {
            if (entity == null) return null!;
            return new TermDto
            {
                Id = entity.word_id,
                Term = entity.word,
                Definition = entity.mean
            };
        }

        // CREATE DTO -> ENTITY (when inserting)
        public static LibraryModels ToEntity(this CreateTermDto dto)
        {
            if (dto == null) return null!;
            return new LibraryModels
            {
                // word_id is generated by the database
                word = dto.Term,
                mean = dto.Definition
            };
        }

        // UPDATE DTO -> apply changes to an existing ENTITY (when updating)
        public static void Apply(this UpdateTermDto dto, LibraryModels entity)
        {
            if (dto == null || entity == null) return;
            entity.word = dto.Term;
            entity.mean = dto.Definition;
        }
    }
}